/* THE DIARIES, one per map (2026-10-01, second pass; the owner: "one per map"). 21 maps, four tiers each, three tasks a tier. Every task is
   something the map really has (tools/diary-mock/scan.mjs reads the rules into maps.json): its monsters, its bosses, its quests, what can be
   gathered there and at what level, its shortcut and nook (v1.1), its lockbox (v1.1), and the world events that can happen on it. Interiors go
   with the map they open from: the Casino with the Yard, the Thieves' Guild with the Gloam, the Crypt with the Boneyard, the Pyramid with the
   Sands, the Tower with the Thunderhead; the Boardwalk's five islands with the Boardwalk.
   A task: [words, icon (an item key or skill_<skill>), what it needs ([skill, level] or null), calvin has done it (the example)].
   An EVENT task ("ev") is done by ANY of the world events that can happen on that map (the owner: "any one of several"); a map where only one
   kind of event can happen (the Carnival, the Vault, the Depths, the Ridge: only Wanted posters) has no event task, so that stays true.
   A "v11" task uses something v1.1 adds (the owner: "make sure the diary includes some events/tasks from v1.1 updates, like new thieving, new
   agility"): a pocket, a lockbox, a shortcut or a nook, a back way, Thrill Hill and its laps, or a set of work clothes. The kind may hold both
   ("ev v11"). */
const S = (k) => `skill_${k}`;
export const DIARIES = [
  { k: "workyard", name: "The Yard", sub: "and the Casino", band: "1–9", em: "r_yard.png",
    perks: ["Bom's counter pays 5% more for what you sell him", "The Gem Sorter's roll costs 10% less", "Raids and the Flood pay 10% more", "A free teleport to the Yard once a day, from anywhere"],
    t: [[["Kill a chicken, a cow and a boar", S("melee"), null, 1], ["Mine copper and tin and catch a sardine", S("mining"), null, 1], ["Finish A Bell for the Broker", S("thieving"), null, 1]],
      [["Finish The Standing Order and An Emerald Edge", S("smithing"), ["smithing", 15], 1], ["Finish Charon's Ledger and The Ferryman's Supper", S("cooking"), ["cooking", 20], 1], ["Get past Dizzy Dale's counter into Thrill Hill", S("agility"), null, 0, "v11"]],
      [["Be in the Yard when a world event there ends: a raid, the Flood or a Wanted poster", S("hp"), null, 1, "ev"], ["Earn a piece of Bronny's leathers from her order", "br_apron", null, 0, "v11"], ["Sort a gem at the Gem Sorter", S("mining"), ["mining", 60], 1]],
      [["Deal the last hit on a raid boss", S("melee"), ["combat", 80], 0], ["Plug a sandbag in the Flood", S("strength"), null, 0], ["Wear a whole set of work clothes", "pr_vest", null, 0, "v11"]]] },
  { k: "gloam", name: "The Gloam", sub: "and the Thieves' Guild", band: "10–19", em: "r_gloam.png",
    perks: ["Trout bite 10% more often here", "Vance's lockpicks cost 10% less", "Gloomwillow chops 10% faster", "The Guild's marks give 10% more Thieving XP"],
    t: [[["Kill a Sulking Toadstool and a Goat in a Toga", S("melee"), ["combat", 10], 1], ["Catch a trout", S("fishing"), ["fishing", 10], 1], ["Finish Grimm's Bow", S("fletching"), null, 1]],
      [["Finish Idle Hands and The First Page", S("wizardry"), null, 1], ["Chop gloomwillow", S("woodcutting"), ["woodcutting", 15], 1], ["Pick a Highwayman's pocket", S("thieving"), ["thieving", 10], 1, "v11"]],
      [["Be in the Gloam when a world event there ends: a star, a poster or the Thief", S("hp"), null, 0, "ev"], ["Mine emerald ore", S("mining"), ["mining", 20], 1], ["Cross the fallen log and chop the deadwood behind the fence", S("agility"), ["agility", 10], 0, "v11"]],
      [["Finish The Weaver's Coil, Marrow and Bone and The Nexus", S("magic"), ["combat", 40], 1], ["Knock a piece of the getaway silks loose from the Jackpot Thief", "gw_jacket", null, 0, "ev v11"], ["Open the Gloam's lockbox", S("thieving"), ["thieving", 15], 0, "v11"]]] },
  { k: "mire", name: "The Lantern Mire", sub: "", band: "20–29", em: "r_gloam.png",
    perks: ["Tax Wraiths and Loan Sharks hit 10% less hard", "Lanternfish bite 10% more often", "Lantern Moths drop their table 10% more often", "Diamond ore mines 10% faster here"],
    t: [[["Finish Lamps Out", S("alchemy"), null, 1], ["Catch a lanternfish", "lanternfish", ["fishing", 20], 1], ["Kill a Paper Twister", S("melee"), ["combat", 20], 1]],
      [["Finish Lights on the Mire", S("melee"), null, 1], ["Finish Glass and Sand", S("alchemy"), null, 1], ["Pick a Loan Shark's pocket", S("thieving"), ["thieving",28], 0, "v11"]],
      [["Be on the Mire when a world event there ends", S("hp"), null, 1, "ev"], ["Mine diamond ore", S("mining"), ["mining", 30], 1], ["Hop the stones between the graves and chop the yew", S("agility"), ["agility", 20], 0, "v11"]],
      [["Finish Lights Out", S("magic"), null, 0], ["Open the Mire's lockbox", S("thieving"), ["thieving",25], 0, "v11"], ["Lift a piece of the Feller's flannels from a pocket", "fl_shirt", null, 0, "v11"]]] },
  { k: "boneyard", name: "The Boneyard", sub: "and the Crypt", band: "30–39", em: "r_bone.png",
    perks: ["Chandelier Spiders drop their table 10% more often", "The Crypt's ante is 10% less", "Bonefish bite 10% more often", "The Crypt's chest has one more roll, once a day"],
    t: [[["Finish Grave Duty", S("melee"), null, 1], ["Kill a Sorry Ghoul and the Stagehand", S("melee"), ["combat", 30], 1], ["Catch a bonefish in the flooded crypt", "bonefish", ["fishing", 30], 1]],
      [["Finish Yew for the Sister and Silk from the Dark", S("woodcutting"), ["woodcutting", 35], 1], ["Clear the Crypt", S("melee"), ["combat", 22], 1], ["Pick the One-Eyed Usher's pocket", S("thieving"), ["thieving",35], 0, "v11"]],
      [["Finish The Sister's Marker and The Sister's Vigil", S("magic"), null, 1], ["Kill the Critic", S("melee"), ["combat", 42], 1], ["Mine dragonstone, and the onyx behind the rail", S("mining"), ["mining", 50], 1, "v11"]],
      [["Clear the Black Crypt", S("melee"), ["combat", 76], 0], ["Kill 100 Chandelier Spiders", S("melee"), ["combat", 34], 1], ["Open the Boneyard's lockbox", S("thieving"), ["thieving", 35], 0, "v11"]]] },
  { k: "cloud", name: "Cloudreach", sub: "", band: "40–49", em: "r_cloud.png",
    perks: ["Sky eel bite 10% more often", "The Star Tent's prices are 5% lower", "Skyash chops 10% faster", "A free teleport to Cloudreach once a day"],
    t: [[["Finish Eels for Zephyr", "skyeel", ["fishing", 40], 1], ["Kill a Cumulus Ram and a Brainstorm", S("melee"), ["combat", 40], 1], ["Mine grimstone", S("mining"), ["mining", 20], 1]],
      [["Finish Rams on the Ridge and Frost on the Page", S("wizardry"), null, 1], ["Chop skyash", S("woodcutting"), ["woodcutting", 45], 1], ["Buy a piece of the stargazer's robes at the Star Tent", "sg_robe", null, 0, "v11"]],
      [["Be in Cloudreach when a world event there ends", S("hp"), null, 0, "ev"], ["Pick an Angel of Minor Inconvenience's pocket", S("thieving"), ["thieving",48], 0, "v11"], ["Climb the cloud steps and chop the rustpine", S("agility"), ["agility", 45], 0, "v11"]],
      [["Kill 100 Angels of Minor Inconvenience", S("magic"), ["combat", 48], 0], ["Mine 200 onyx ore", S("mining"), ["mining", 50], 0], ["Open Cloudreach's lockbox", S("thieving"), ["thieving", 48], 0, "v11"]]] },
  { k: "sands", name: "The Golden Sands", sub: "and the Great Pyramid", band: "40–49", em: "r_bone.png",
    perks: ["Oasis perch bite 10% more often", "The Sands' monsters hit 10% less hard", "The Pyramid's chest has one more roll, once a day", "A free teleport to the Golden Sands once a day"],
    t: [[["Finish Rashid's Sample", S("mining"), ["mining", 50], 1], ["Dig sand and catch an oasis perch", S("fishing"), ["fishing", 40], 1], ["Kill a Bandaged Debtor", S("melee"), ["combat", 43], 1]],
      [["Finish The Caravan Road", S("agility"), null, 1], ["Chop palm logs", S("woodcutting"), ["woodcutting", 45], 1], ["Pick a Bandaged Debtor's pocket", S("thieving"), ["thieving",44], 0, "v11"]],
      [["Clear the Great Pyramid", S("melee"), ["combat", 55], 0], ["Finish Fangs and Oasis Supper", S("cooking"), null, 1], ["Be on the Sands when a world event there ends", S("hp"), null, 0, "ev"]],
      [["Open the Sands' lockbox", S("thieving"), ["thieving",45], 0, "v11"], ["Get the Coilling from the Pyramid", S("breeding"), null, 0], ["Swing between the obelisks and chop the rustpine", S("agility"), ["agility", 40], 0, "v11"]]] },
  { k: "thunderhead", name: "The Thunderhead", sub: "and the Tower", band: "50–60", em: "r_cloud.png",
    perks: ["Storm marlin bite 10% more often", "Storm Golems and Thunderwolves hit 10% less hard", "Starfall ore mines 10% faster", "The Storm Drain needs no Agility level"],
    t: [[["Kill a Storm Golem and a Thunder Goose", S("melee"), ["combat", 52], 1], ["Catch a storm marlin", S("fishing"), ["fishing", 50], 1], ["Finish The Rod", S("smithing"), null, 1]],
      [["Finish Wild Goose and Storm in a Bottle", S("magic"), null, 1], ["Mine starfall ore", "starfall_ore", ["mining", 60], 1], ["Climb a floor of the Tower", S("melee"), ["combat", 50], 1]],
      [["Crawl the Storm Drain down to the Yard", S("agility"), ["agility",61], 0, "v11"], ["Kill the House", S("melee"), ["combat", 70], 1], ["Mine voidglass behind the runestones", "voidglass", ["mining", 70], 0, "v11"]],
      [["Reach the top of the Tower", S("melee"), ["combat", 90], 0], ["Open the Thunderhead's lockbox", S("thieving"), ["thieving",55], 0, "v11"], ["Be on the Thunderhead when a world event there ends", S("hp"), null, 0, "ev"]]] },
  { k: "carnival", name: "The Carnival", sub: "", band: "62–72", em: "r_carn.png",
    perks: ["The stalls cost 10% less to play", "Prize goldfish bite 10% more often", "Catalytic converters come off 10% faster", "A free teleport to the Carnival once a day"],
    t: [[["Pick a Pinhead's pocket", S("thieving"), ["thieving",58], 0, "v11"], ["Win a prize at a stall", S("thieving"), null, 1], ["Catch a prize goldfish", S("fishing"), ["fishing", 62], 1]],
      [["Kill the Triple and the Fat Lady", S("magic"), ["combat", 68], 0], ["Pull a catalytic converter", S("mining"), ["mining", 65], 1], ["Chop rustpine", S("woodcutting"), ["woodcutting", 65], 1]],
      [["Kill the Strongman", S("strength"), ["combat", 71], 0], ["Squeeze through the bent bars and chop the vaultwood", S("agility"), ["agility", 60], 0, "v11"], ["Win a prize at every stall on the midway", S("thieving"), null, 0]],
      [["Finish The Grinning Debt", S("melee"), ["combat", 72], 0], ["Open the Carnival's lockbox", S("thieving"), ["thieving",65], 0, "v11"], ["Take the Scrap Run to the Trailer Park", S("agility"), ["agility", 70], 0, "v11"]]] },
  { k: "boardwalk", name: "The Boardwalk", sub: "and its five islands", band: "66–78", em: "r_carn.png",
    perks: ["A free teleport to the Boardwalk once a day", "Mackerel bite 10% more often", "Deckhands and Kraken Arms hit 10% less hard", "Captain Claw's chest has one more roll, once a day"],
    t: [[["Finish Mackerel Sky", S("fishing"), ["fishing", 60], 1], ["Kill a Gull and a Deckhand", S("archery"), ["combat", 66], 1], ["Cook a mackerel", S("cooking"), null, 1]],
      [["Row out to every island", S("agility"), null, 1], ["Chop palm logs on the strand", S("woodcutting"), ["woodcutting", 60], 1], ["Pick a Deckhand's pocket", S("thieving"), ["thieving", 70], 0, "v11"]],
      [["Finish Knives on the Plaza", S("melee"), ["combat", 70], 0], ["Kill a Kraken Arm", S("archery"), ["combat", 78], 0], ["Swing under the pier", S("agility"), ["agility", 66], 0, "v11"]],
      [["Finish Captain Claw", S("melee"), ["combat", 80], 0], ["Open the Boardwalk's lockbox", S("thieving"), ["thieving",72], 0, "v11"], ["Be on the Boardwalk when a world event there ends", S("hp"), null, 0, "ev"]]] },
  { k: "trailer", name: "The Trailer Park", sub: "", band: "80–99", em: "r_vault.png",
    perks: ["Bom pays 10% more for catalytic converters", "Mud cat bite 10% more often", "Slagstone and singularity mine 10% faster here", "A free teleport to the Trailer Park once a day"],
    t: [[["Finish The Scrap Line", S("mining"), ["mining", 65], 0], ["Kill a Junkyard Dog", S("melee"), ["combat", 80], 0], ["Chop rustpine and bogwood", S("woodcutting"), ["woodcutting", 80], 0]],
      [["Finish The King of the Yard", S("melee"), ["combat", 90], 0], ["Catch a mud cat", S("fishing"), ["fishing", 80], 0], ["Pick the Scrapper's pocket", S("thieving"), ["thieving",84], 0, "v11"]],
      [["Open the Trailer Park's lockbox", S("thieving"), ["thieving",85], 0, "v11"], ["Mine slagstone", S("mining"), ["mining", 85], 0], ["Climb the fence and mine the fossil in the corner", S("agility"), ["agility", 80], 0, "v11"]],
      [["Get the whole of Sal's spare overalls", "sl_overalls", ["combat",95], 0, "v11"], ["Mine singularity ore", S("mining"), ["mining", 90], 0], ["Be in the Trailer Park when a world event there ends", S("hp"), null, 0, "ev"]]] },
  { k: "vault", name: "The Vault", sub: "", band: "74–92", em: "r_vault.png",
    perks: ["Vault Wardens notice you a tile later", "Cloud rays bite 10% more often", "Eclipse and nova ore mine 10% faster here", "The Last Dealer drops his table 10% more often"],
    t: [[["Kill a Vault Warden", S("melee"), ["combat", 74], 1], ["Mine starfall ore here", S("mining"), ["mining", 60], 1], ["Catch a cloud ray", S("fishing"), ["fishing", 60], 1]],
      [["Finish The Audit", S("thieving"), ["thieving", 40], 0], ["Mine eclipse ore", "eclipse_ore", ["mining", 70], 0], ["Chop vaultwood", S("woodcutting"), ["woodcutting", 75], 0]],
      [["Finish Vaultwood and Count the Hoard", S("woodcutting"), ["woodcutting", 75], 0], ["Kill the Pit Boss and a Coin Hoard", S("melee"), ["combat", 86], 0], ["Pick a Vault Warden's pocket", S("thieving"), ["thieving",78], 0, "v11"]],
      [["Kill the Last Dealer 10 times", S("melee"), ["combat", 92], 0], ["Pick the Last Dealer's pocket", S("thieving"), ["thieving",88], 0, "v11"], ["Kill 25 Coin Hoards", S("melee"), ["combat", 86], 0]]] },
  { k: "depths", name: "The Depths of the Mountain", sub: "", band: "73–84", em: "r_vault.png",
    perks: ["Abyss crystal mines 10% faster", "Ogres here hit 10% less hard", "Gems turn up 10% more often in the Depths", "The Deepwarden's drop table rolls twice on your first kill each day"],
    t: [[["Finish Pink in the Dark", S("mining"), ["mining", 70], 0], ["Kill a Pot Boy and an Abyss Wisp", S("melee"), ["combat", 73], 0], ["Pick a Pot Boy's pocket", S("thieving"), ["thieving",73], 0, "v11"]],
      [["Finish Cutters", S("melee"), ["combat", 75], 0], ["Mine abyss crystal", S("mining"), ["mining", 75], 0], ["Kill a Crystal Ogre and an Iron Ogre", S("melee"), ["combat", 80], 0]],
      [["Finish The Keeper of the Mountain", S("melee"), ["combat", 84], 0], ["Kill the Deepwarden", S("melee"), ["combat", 84], 0], ["Climb the rope and mine the slag bank", S("agility"), ["agility", 75], 0, "v11"]],
      [["Kill the Deepwarden 25 times", S("melee"), ["combat", 90], 0], ["Open the Depths' lockbox", S("thieving"), ["thieving",78], 0, "v11"], ["Find the Mountain's Heart", S("mining"), ["mining", 80], 0]]] },
  { k: "valley", name: "The Primeval Valley", sub: "the Lowlands", band: "90–98", em: "r_north.png",
    perks: ["Coelacanth bite 10% more often", "Cycads chop 10% faster", "Cavemen's rocks hit 10% less hard", "A free teleport to the Primeval Valley once a day"],
    t: [[["Walk into the Primeval Valley", S("agility"), null, 0], ["Pick a Caveman's pocket", S("thieving"), ["thieving",90], 0, "v11"], ["Catch a coelacanth", S("fishing"), ["fishing", 92], 0]],
      [["Kill a Sabretooth and a Pterodactyl", S("archery"), ["combat", 95], 0], ["Chop a cycad", S("woodcutting"), ["woodcutting", 92], 0], ["Take the vine over the fence and chop the frostpine", S("agility"), ["agility", 90], 0, "v11"]],
      [["Kill a Woolly Mammoth", S("archery"), ["combat", 98], 0], ["Take the Ice Ledge to the Frozen Reach", S("agility"), ["agility", 92], 0, "v11"], ["Be in the Valley when a world event there ends", S("hp"), null, 0, "ev"]],
      [["Kill the Mammoth Matriarch", S("archery"), ["combat", 100], 0], ["Kill 100 Cavemen", S("archery"), ["combat", 90], 0], ["Open the Valley's lockbox", S("thieving"), ["thieving", 92], 0, "v11"]]] },
  { k: "valley_ridge", name: "The Primeval Ridge", sub: "", band: "95–103", em: "r_north.png",
    perks: ["Fossil rocks mine 10% faster here", "Raptors notice you a tile later", "Elder Pterodactyls drop their table 10% more often", "A free teleport to the Ridge once a day"],
    t: [[["Walk up onto the Ridge", S("agility"), null, 0], ["Kill a Raptor", S("melee"), ["combat", 100], 0], ["Mine a fossil rock", S("mining"), ["mining", 92], 0]],
      [["Kill a Caveman Hunter", S("archery"), ["combat", 100], 0], ["Kill an Elder Pterodactyl", S("archery"), ["combat", 103], 0], ["Chop a cycad on the Ridge", S("woodcutting"), ["woodcutting", 92], 0]],
      [["Kill 50 Raptors", S("melee"), ["combat", 100], 0], ["Mine 100 fossil", S("mining"), ["mining", 92], 0], ["Chop 100 cycads on the Ridge", S("woodcutting"), ["woodcutting", 92], 0]],
      [["Kill 100 Elder Pterodactyls", S("archery"), ["combat", 103], 0], ["Kill the Golden Raptor", S("melee"), ["combat", 100], 0], ["Pick a Caveman Hunter's pocket", S("thieving"), ["thieving",96], 0, "v11"]]] },
  { k: "valley_lair", name: "Old Rex's Lair", sub: "", band: "97–110", em: "r_north.png",
    perks: ["Tar Pit Horrors hit 10% less hard", "Fossil comes up two at a time, one in ten", "Old Rex's drop table rolls twice on your first kill each day", "Raptors and Tar Pit Horrors notice you a tile later"],
    t: [[["Walk into the Lair", S("agility"), null, 0], ["Kill a Tar Pit Horror", S("melee"), ["combat", 105], 0], ["Mine fossil in the Lair", S("mining"), ["mining", 92], 0]],
      [["Kill 25 Tar Pit Horrors", S("melee"), ["combat", 105], 0], ["Kill a Raptor in the Lair", S("archery"), ["combat", 100], 0], ["Kill an Elder Pterodactyl over the volcano", S("archery"), ["combat", 103], 0]],
      [["Kill Old Rex", S("archery"), ["combat", 108], 0], ["Kill Old Rex 10 times", S("archery"), ["combat", 108], 0], ["Get a Rex tooth", S("archery"), ["combat", 108], 0]],
      [["Get the Rexling", S("breeding"), null, 0], ["Get Old Rex's necklace", S("archery"), ["combat", 110], 0], ["Kill Old Rex 50 times", S("archery"), ["combat", 110], 0]]] },
  { k: "frozen", name: "The Frozen Reach", sub: "", band: "95–108", em: "r_north.png",
    perks: ["The cold hurts 10% less", "Icefin bite 10% more often", "Glacite mines 10% faster", "See when the Ice Wyrm will next rise, in the Diary tab"],
    t: [[["Walk into the Frozen Reach", S("agility"), null, 0], ["Kill a Frost Wolf with a spell", S("magic"), ["magic", 60], 0], ["Catch an icefin", "icefin", ["fishing", 94], 0]],
      [["Kill a Snow Owl and a Yeti", S("magic"), ["combat", 104], 0], ["Mine glacite", "glacite", ["mining", 94], 0], ["Chop frostpine", S("woodcutting"), ["woodcutting", 94], 0]],
      [["Kill a Frost Wraith", S("magic"), ["combat", 106], 0], ["Hop the ice steps and chop the frostpine", S("agility"), ["agility", 95], 0, "v11"], ["Make a Frostpine wand", S("wizardry"), ["wizardry", 97], 0]],
      [["Be there when the Ice Wyrm dies", S("magic"), ["combat", 110], 0, "ev"], ["Get the Wyrmling or the Blizzard Owl", S("breeding"), null, 0], ["Open the Reach's lockbox", S("thieving"), ["thieving", 97], 0, "v11"]]] },
  { k: "frostspire", name: "The Frostspire", sub: "", band: "99–115", em: "r_north.png",
    perks: ["Frost Giants' boulders hit 10% less hard", "Glacite and frostpine 10% faster here", "The Frost Jarl's drop table rolls twice on your first kill each day", "A free teleport to the Frostspire once a day"],
    t: [[["Climb to the Frostspire", S("agility"), null, 0], ["Kill an Ice Elemental", S("magic"), ["combat", 110], 0], ["Catch an icefin through the tarn", S("fishing"), ["fishing", 94], 0]],
      [["Kill a Frost Giant", S("magic"), ["combat", 112], 0], ["Pluck a piece of the bowyer's greens from a Hail Drake or a Snow Owl", "bw_jerkin", null, 0, "v11"], ["Mine glacite on the Spire", S("mining"), ["mining", 94], 0]],
      [["Kill the Frost Jarl", S("magic"), ["combat", 113], 0], ["Get a Frostbite ring", S("magic"), ["magic", 85], 0], ["Wear the Crown of the Frost Jarl", S("magic"), null, 0]],
      [["Kill the Frost Jarl 25 times", S("magic"), ["combat", 113], 0], ["Get the Jarl's Hound", S("breeding"), null, 0], ["Make the Rimeheart", S("wizardry"), ["wizardry", 98], 0]]] },
  { k: "wild", name: "The Wilderness", sub: "PvP", band: "any", em: "r_wild.png", pvp: true,
    perks: ["See how many people are in the Wilderness, in the Diary tab", "A death in the Wilderness costs a fifth less", "Gloomfin bite 10% more often in the Wild", "A free trip into the Wilderness once a day, from anywhere"],
    t: [[["Walk into the Wilderness", S("agility"), null, 1], ["Kill anything in the Wild", S("melee"), null, 1], ["Chop deadwood or mine grimstone in the Wild", S("woodcutting"), null, 1]],
      [["Kill a player in the Wilderness", S("melee"), null, 0, "pvp"], ["Catch a gloomfin in the Wild", S("fishing"), ["fishing", 20], 0], ["Pick a Goblin Cutter's or a Vault Warden's pocket in the Wild", S("thieving"), ["thieving",76], 0, "v11"]],
      [["Kill 10 players in the Wilderness", S("melee"), null, 0, "pvp"], ["Kill a player in the Wild with a bow or a spell", S("thieving"), null, 0, "pvp"], ["Kill a Goblin Cutter and a Crystal Ogre", S("melee"), ["combat", 78], 0]],
      [["Kill a player 10 or more combat levels above you", S("melee"), null, 0, "pvp"], ["Kill 3 players in one trip without dying", S("melee"), null, 0, "pvp"], ["Mine 100 dragonstone in the Wild", S("mining"), ["mining", 40], 0]]] },
  { k: "deep", name: "The Deep Wild", sub: "PvP", band: "any", em: "r_wild.png", pvp: true,
    perks: ["See how many people are in the Deep Wild, in the Diary tab", "Voidfin bite 10% more often", "Gallows logs chop 10% faster", "Your gear is half as likely to drop when you die in the Deep Wild"],
    t: [[["Reach the Deep Wild", S("agility"), ["combat", 50], 0], ["Kill a Grim Lich", S("magic"), ["combat", 66], 0], ["Mine onyx or chop skyash in the Deep Wild", S("mining"), ["mining", 50], 0]],
      [["Kill a player in the Deep Wild", S("melee"), null, 0, "pvp"], ["Mine starfall in the Deep Wild", S("mining"), ["mining", 60], 0], ["Pick a Caveman's or the Scrapper's pocket in the Deep Wild", S("thieving"), ["thieving", 84], 0, "v11"]],
      [["Kill 10 players in the Deep Wild", S("melee"), null, 0, "pvp"], ["Chop gallows logs", S("woodcutting"), ["woodcutting", 90], 0], ["Catch a voidfin", S("fishing"), ["fishing", 92], 0]],
      [["Kill a player 10 or more combat levels above you in the Deep Wild", S("melee"), null, 0, "pvp"], ["Kill 25 players in the Deep Wild", S("melee"), null, 0, "pvp"], ["Catch 100 voidfin", S("fishing"), ["fishing", 92], 0]]] },
  { k: "thrill", name: "Thrill Hill", sub: "v1.1", band: "1–70", em: "r_carn.png",
    perks: ["Fast Eddie's goods cost 10% fewer marks", "Featherwood gives one more feather", "The Pro Run's laps pay 10% more", "The cannon never misfires (no slips on it)"],
    t: [[["Run a lap of the Rookie Run", S("agility"), null, 0, "v11"], ["Buy a corn dog from Corndog Carl", S("cooking"), null, 0, "v11"], ["Talk to Fast Eddie", S("thieving"), null, 0, "v11"]],
      [["Run a lap of the Pro Run", S("agility"), ["agility", 40], 1, "v11"], ["Get over the scrap into the Junk Mound", S("agility"), ["agility", 50], 0, "v11"], ["Chop featherwood", S("woodcutting"), ["woodcutting", 60], 1, "v11"]],
      [["Pick a Grease Gremlin's pocket", S("thieving"), ["thieving", 45], 0, "v11"], ["Run 50 laps of the Rookie or Pro Run", S("agility"), null, 0, "v11"], ["Find a piece of the Prospector's kit on a lap", "pr_vest", null, 0, "v11"]],
      [["Fire yourself out of the cannon", S("agility"), ["agility", 70], 0, "v11"], ["Run 100 laps of the Pro Run", S("agility"), ["agility", 40], 0, "v11"], ["Buy the stunt leathers", S("agility"), ["agility", 60], 0, "v11"]]] },
  { k: "thrill_top", name: "Daredevil Peak", sub: "v1.1", band: "70–92", em: "r_carn.png",
    perks: ["Nitro eels bite 10% more often", "Hellbikers notice you a tile later", "Big Daddy Crusher's drop table rolls twice on your first kill each day", "A free teleport to Daredevil Peak once a day"],
    t: [[["Land on Daredevil Peak", S("agility"), ["agility", 70], 0, "v11"], ["Kill a Hellbiker", S("melee"), ["combat", 75], 1, "v11"], ["Catch a nitro eel", S("fishing"), ["fishing", 75], 0, "v11"]],
      [["Run a lap of the Champion Run", S("agility"), ["agility", 70], 0, "v11"], ["Pick a Hellbiker's pocket", S("thieving"), ["thieving", 70], 0, "v11"], ["Cook a nitro eel", S("cooking"), ["cooking", 75], 0, "v11"]],
      [["Get up the crusher ramp to the Peak", S("agility"), ["agility", 90], 0, "v11"], ["Mine chrome", S("mining"), ["mining", 85], 0, "v11"], ["Kill Big Daddy Crusher", S("melee"), ["combat", 92], 0, "v11"]],
      [["Run 100 laps of the Champion Run", S("agility"), ["agility", 70], 0, "v11"], ["Get Lil' Crusher", S("breeding"), null, 0, "v11"], ["Wear chrome-toe boots you smithed yourself", S("smithing"), ["smithing", 85], 0, "v11"]]] }];
